version: '3.9'

services:
  dbShip:
    image: postgres:15
    container_name: postgres-base
    volumes:
      - db:/var/lib/postgresq/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=haslo123
      - POSTGRES_DB=battlebase
    ports:
      - 5432:5432

  appweb:
      build:
        dockerfile: Dockerfile
        context: .
      container_name: webmodule
      environment:
       SPRING_DATASOURCE_URL: jdbc:postgresql://dbShip:5432/battlebase
      ports:
        - 8080:8080
      depends_on:
        - dbShip

volumes:
  db: